"""sync ORM models

Revision ID: c520a505929c
Revises: 17552ae6ada1
Create Date: 2025-09-26 21:18:59.087597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c520a505929c'
down_revision: Union[str, Sequence[str], None] = '17552ae6ada1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alert_tenant_id'), table_name='alert')
    op.drop_index(op.f('ix_cash_movement_tenant_id'), table_name='cash_movement')
    op.drop_index(op.f('ix_location_tenant_id'), table_name='location')
    op.create_index('ix_location_tenant', 'location', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.create_index('ix_product_tenant', 'product', ['tenant_id'], unique=False)
    op.drop_index(op.f('ix_sale_tenant_id'), table_name='sale')
    op.drop_index(op.f('ix_sale_item_tenant_id'), table_name='sale_item')
    op.create_index('ix_sale_item_product', 'sale_item', ['product_id'], unique=False)
    op.create_index('ix_sale_item_sale', 'sale_item', ['sale_id'], unique=False)
    op.drop_index(op.f('ix_sale_tender_tenant_id'), table_name='sale_tender')
    op.create_index('ix_sale_tender_sale', 'sale_tender', ['sale_id'], unique=False)
    op.drop_index(op.f('ix_stock_movement_tenant_id'), table_name='stock_movement')
    op.create_index('ix_stock_movement_tpl', 'stock_movement', ['tenant_id', 'product_id', 'location_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_movement_tpl', table_name='stock_movement')
    op.create_index(op.f('ix_stock_movement_tenant_id'), 'stock_movement', ['tenant_id'], unique=False)
    op.drop_index('ix_sale_tender_sale', table_name='sale_tender')
    op.create_index(op.f('ix_sale_tender_tenant_id'), 'sale_tender', ['tenant_id'], unique=False)
    op.drop_index('ix_sale_item_sale', table_name='sale_item')
    op.drop_index('ix_sale_item_product', table_name='sale_item')
    op.create_index(op.f('ix_sale_item_tenant_id'), 'sale_item', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_sale_tenant_id'), 'sale', ['tenant_id'], unique=False)
    op.drop_index('ix_product_tenant', table_name='product')
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.drop_index('ix_location_tenant', table_name='location')
    op.create_index(op.f('ix_location_tenant_id'), 'location', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_cash_movement_tenant_id'), 'cash_movement', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_alert_tenant_id'), 'alert', ['tenant_id'], unique=False)
    # ### end Alembic commands ###
